import Auth from './auth'
import Login from './auth/login'
import Register from './auth/register'
import ForgotPassword from './auth/forgot-password'
import Protected from './protected'
import Protectedauth from './protectedAuth'
import Settings from './settings'
import Brands from './brands'
import Products from './products'
import Categories from './category'
import Home from './home'
import Single_Category from './category-single'
import Brand_Category from './brand-category'
import Product_detail from './product-details'
import Stock from './stock'

export {Stock,Auth, Login, Register, ForgotPassword, Protected, Protectedauth, Categories, Brands,Settings, Products, Home, Single_Category, Brand_Category, Product_detail}